### ISSUE TITLE
Firefox 51 and FirePath 0.9.7.1.1 not displaying xpath option

### ISSUE THREAD

**Issue by mboomer** [pierretholence/firepath#59]
I have installed FireFox 51 and installed the latest version of FirePath and FireBug but when I right click on an element I do not get the xpath tab.

I do not have any other extensions installed?

**Comment by dinesh160592** [comment]
@mboomer same for me :( from the morning I'm struggling...

**Comment by pierretholence** [comment]
I tested FirePath in Firefox 51 and it works fine for me.
One thing that could be causing the issue is that your Firefox may have switched to "Multi-process" mode which Firebug and FirePath are not compatible with.
You can check if Firefox is in "Multi-process" mode by looking at the Firefox Options. At the top of the General section there should be a "Enable multi-process Firefox" checkbox. If it is checked, you can try to uncheck it and restart Firefox.

Let me know if it fixes the issue.

**Comment by mboomer** [comment]
I couldn't find the multi process option in the Firefox options but I did confirm the settings using about:support and then changed the setting using about:config. 

I changed browser.tabs.remote.autostart.2 to false and restarted the browser and xpath now appears when I need it.

Thanks for pointing me in the right direction
